# Generated by Django 5.2 on 2025-05-25 11:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_progress_start_date_project_progress_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(error_messages={'invalid': 'يرجى إدخال تاريخ صالح.'}, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 5, 25))], verbose_name='تاريخ الاستحقاق'),
        ),
    ]
