# Generated by Django 5.2 on 2026-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_notes_task_notes_projectassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='assigned_by_employee',
            field=models.BooleanField(default=True, verbose_name='تم التعيين من خلال موظف'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_by_employee',
            field=models.BooleanField(default=True, verbose_name='تم التعيين من خلال موظف'),
        ),
    ]
