# Generated by Django 5.2 on 2026-01-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectassignment_assigned_by_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='user',
        ),
    ]
